#ifndef FIREWORK_PATTERN_H
#define FIREWORK_PATTERN_H

typedef enum FireworkPattern {
    PATTERN_COMET,
    PATTERN_CROSSETTE,
    PATTERN_PEONY,
    PATTERN_RING,
    PATTERN_WILLOW,
    PATTERN_PALM,
    PATTERN_FISH,
    PATTERN_STROBE,
    PATTERN_GHOST,
    PATTERN_TOURBILLION,
    PATTERN_NISHIKI_KAMURO,
    PATTERN_CHRYSANTHEMUM,
    PATTERN_COUNT
} FireworkPattern;

#endif // FIREWORK_PATTERN_H
